
one_wire:
  - platform: gpio
    pin: GPIO02
    id: dallas_bus

sensor:
  - platform: internal_temperature
    name: ${internal_esp_temperature}
    entity_category: diagnostic
    unit_of_measurement: "°C"
    device_class: temperature
    accuracy_decimals: 1

# dallas temp sensors
  - platform: dallas_temp
    id: DS18B20_0
    index: 0
    name: "DS18B20 1"
    update_interval: 60s
    resolution: 12
  - platform: dallas_temp
    id: DS18B20_1
    index: 1
    name: "DS18B20 2"
    update_interval: 60s
    resolution: 12

  - platform: template
    name: "DS18B20 Delta T"
    lambda: |-
      return abs(id(DS18B20_0).state - id(DS18B20_1).state);
    accuracy_decimals: 1
    unit_of_measurement: "°C"

number:
  # 1. Hysteresis (Deadband)
  - platform: template
    name: "Asgard Hysteresis"
    id: thermostat_hysteresis
    icon: "mdi:arrow-expand-vertical"
    unit_of_measurement: "°C"
    min_value: 0.1
    max_value: 2.0
    step: 0.1
    restore_value: true
    initial_value: 0.5
    optimistic: true
    on_value:
      then:
        - lambda: |-
            id(virtual_climate_z1).set_heat_deadband(x);
            id(virtual_climate_z1).set_heat_overrun(x);
            id(virtual_climate_z1).set_cool_deadband(x);
            id(virtual_climate_z1).set_cool_overrun(x);

            ${z2_cpp_prefix} id(virtual_climate_z2).set_heat_deadband(x);
            ${z2_cpp_prefix} id(virtual_climate_z2).set_heat_overrun(x);
            ${z2_cpp_prefix} id(virtual_climate_z2).set_cool_deadband(x);
            ${z2_cpp_prefix} id(virtual_climate_z2).set_cool_overrun(x);
