substitutions:
  uart_rx_pin: 38
  uart_tx_pin: 39
  uart_proxy_rx_pin: 8
  uart_proxy_tx_pin: 7
  led_gpio_pin: 42
  # enable asgard prefixes
  asgard_prefix: ""
  z2_dashboard: !include
    file: asgard-dashboard-z2.yaml
  z2_thermostat: !include
    file: asgard-thermostat.yaml
    vars: 
      zone_identifier: "z2"
      gpio: "GPIO41"

<<: !include proxy-base.yaml
<<: !include asgard-sensors.yaml
<<: !include slave.yaml

packages:
 thermostat-room-0: !include { file: asgard-thermostat.yaml, vars: { zone_identifier: "z1", gpio: "GPIO40" } }
 thermostat-room-1: ${ z2_thermostat if z2_enabled else {} }
 dashboard-z1: !include asgard-dashboard-z1.yaml
 dashboard-z2: ${ z2_dashboard if z2_enabled else {} }

