esphome:
  includes:
    - optimizer/optimizer.h
  on_boot:
      priority: -100.0
      then:
        - lambda: optimizer.update_boost_sensor();
        - lambda: optimizer.check_lockout_expiration();

substitutions:
  update_interval_minutes: "10min"

globals:
  - id: lockout_expiration_timestamp
    type: uint32_t
    restore_value: yes
    initial_value: '0'

number:
  # Safety limits z1
  - platform: template
    id: maximum_heating_flow_temp
    name: ${maximum_heating_flow_temp}
    unit_of_measurement: "°C"
    optimistic: true
    restore_value: true
    initial_value: 35.0
    min_value: 25.0
    max_value: 55.0
    step: 0.5
  - platform: template
    id: minimum_heating_flow_temp
    name: ${minimum_heating_flow_temp}
    unit_of_measurement: "°C"
    optimistic: true
    restore_value: true
    initial_value: 25.0
    min_value: 24.0
    max_value: 40.0
    step: 0.5

  - platform: template
    id: maximum_heating_flow_temp_z2
    name: ${maximum_heating_flow_temp} z2
    unit_of_measurement: "°C"
    optimistic: true
    restore_value: true
    initial_value: 35.0
    min_value: 25.0
    max_value: 55.0
    step: 0.5
  - platform: template
    id: minimum_heating_flow_temp_z2
    name: ${minimum_heating_flow_temp} z2
    unit_of_measurement: "°C"
    optimistic: true
    restore_value: true
    initial_value: 25.0
    min_value: 24.0
    max_value: 40.0
    step: 0.5
  
  # cooling vars
  - platform: template
    id: minimum_cooling_flow_temp
    name: ${minimum_cooling_flow_temp}
    unit_of_measurement: "°C"
    optimistic: true
    restore_value: true
    initial_value: 18.0
    min_value: 10.0
    max_value: 25.0
    step: 0.5
  - platform: template
    id: cooling_smart_start_temp
    unit_of_measurement: "°C"
    name: ${cooling_smart_start_temp}
    optimistic: true
    restore_value: true
    initial_value: 19.0
    min_value: 16.0
    max_value: 22.0
    step: 0.5
  # general
  - platform: template
    id: auto_adaptive_setpoint_bias
    unit_of_measurement: "°C"
    name: ${auto_adaptive_setpoint_bias}
    optimistic: true
    restore_value: true
    initial_value: 0.0
    min_value: -2.5
    max_value: 2.5
    step: 0.1
  # Temperature feedback via api
  - platform: template
    id: temperature_feedback_z1
    name: ${temperature_feedback} z1
    unit_of_measurement: "°C"
    optimistic: true
    restore_value: true
    initial_value: 20.0
    min_value: -50
    max_value: 100
    step: 0.1
  - platform: template
    id: temperature_feedback_z2
    name: ${temperature_feedback} z2
    unit_of_measurement: "°C"
    optimistic: true
    restore_value: true
    initial_value: 20.0
    min_value: -50
    max_value: 100
    step: 0.1

    #short cycle vars
  - platform: template
    # Short-cycle protection
    id: minimum_compressor_on_time
    name: ${minimum_compressor_on_time}
    optimistic: true
    restore_value: true
    initial_value: 5 # minutes
    min_value: 1
    max_value: 20
    step: 1
  - platform: template
    id: predictive_short_cycle_high_delta_time_window
    name: ${predictive_short_cycle_high_delta_time_window}
    unit_of_measurement: "min"
    optimistic: true
    restore_value: true
    initial_value: 4.0
    min_value: 1.0
    max_value: 5.0
    step: 0.5

select:
  - platform: template
    id: temperature_feedback_source
    name: ${temperature_feedback_source}
    optimistic: true
    restore_value: true
    options:
      - "${temperature_feedback_option_room}"
      - "${select_feedback_option_api}"
    initial_option: "${temperature_feedback_option_room}"

  - platform: template
    id: heating_system_type
    name: ${heating_system_type}
    optimistic: true
    restore_value: true
    options:
      - "${heating_system_type_option_ufh}"
      - "${heating_system_type_option_ufh} *"
      - "${heating_system_type_option_ufh_rad}"
      - "${heating_system_type_option_ufh_rad} *"
      - "${heating_system_type_option_rad}" 
      - "${heating_system_type_option_rad} *"
    initial_option: "${heating_system_type_option_ufh}"

  - platform: template
    id: lockout_duration
    name: ${lockout_duration}
    optimistic: true
    restore_value: true
    options:
      - "0"
      - "15"
      - "30"
      - "45"
      - "60"
    initial_option: "0"
  
switch:
  - platform: template
    name: ${auto_adaptive_control_enabled}
    id: auto_adaptive_control_enabled
    restore_mode: RESTORE_DEFAULT_OFF
    optimistic: true

  - platform: template
    name: ${predictive_short_cycle_control_enabled}
    id: predictive_short_cycle_control_enabled
    restore_mode: RESTORE_DEFAULT_OFF
    optimistic: true
    turn_on_action:
      - lambda: optimizer.reset_predictive_boost();
    turn_off_action:
      - lambda: optimizer.reset_predictive_boost();

binary_sensor:
  - platform: template
    id: status_predictive_boost_active
    name: ${status_predictive_boost_active}
    lambda: |-
      return optimizer.get_predictive_boost_state();
  - platform: ecodan
    status_short_cycle_lockout:
      id: status_short_cycle_lockout
      name: ${status_short_cycle_lockout}
    status_compressor:
      id: status_compressor
      name: ${status_compressor}
      on_state_change:
        then:
          - lambda: |-
              if (x.has_value() && x_previous.has_value()) {
                optimizer.on_compressor_state_change(x.value(), x_previous.value());
              }

button:
  - platform: template
    id: short_cycle_mitigation_button
    name: ${short_cycle_mitigation_button}
    on_press:
      - logger.log:
          level: INFO
          format: "Lockout script cancelled by button"
      - lambda: optimizer.restore_svc_state();

  # - platform: template
  #   name: 'Auto-Adaptive: Run'
  #   id: run_auto_adaptive_cycle
  #   icon: "mdi:play-circle"
  #   on_press:
  #     then:
  #       - script.execute: auto_adaptive_loop

  # - platform: template
  #   name: "Short-Cycle: Start Compressor (Simulated)"
  #   on_press:
  #     - lambda: |-
  #         id(status_compressor).publish_state(true);

  # - platform: template
  #   name: "Short-Cycle: Stop Compressor (Simulated)"
  #   on_press:
  #     - lambda: |-
  #         id(status_compressor).publish_state(false);

interval:
  - interval: ${update_interval_minutes}
    then:
      - lambda: optimizer.run_auto_adaptive_loop();
  - interval: 30s
    then:
      - lambda: optimizer.check_lockout_expiration();
      - lambda: optimizer.predictive_short_cycle_check();
      - lambda: optimizer.update_boost_sensor();