substitutions:
  update_interval_minutes: "10min"

number:
  # Safety limits
  - platform: template
    id: maximum_heating_flow_temp
    name: ${maximum_heating_flow_temp}
    unit_of_measurement: "°C"
    optimistic: true
    restore_value: true
    initial_value: 38.0
    min_value: 25.0
    max_value: 55.0
    step: 0.5
  - platform: template
    id: minimum_cooling_flow_temp
    name: ${minimum_cooling_flow_temp}
    unit_of_measurement: "°C"
    optimistic: true
    restore_value: true
    initial_value: 18.0
    min_value: 10.0
    max_value: 25.0
    step: 0.5
  - platform: template
    id: minimum_heating_flow_temp
    name: ${minimum_heating_flow_temp}
    unit_of_measurement: "°C"
    optimistic: true
    restore_value: true
    initial_value: 25.0
    min_value: 24.0
    max_value: 40.0
    step: 0.5
  - platform: template
    id: cooling_smart_start_temp
    unit_of_measurement: "°C"
    name: ${cooling_smart_start_temp}
    optimistic: true
    restore_value: true
    initial_value: 19.0
    min_value: 16.0
    max_value: 22.0
    step: 0.5
  - platform: template
    id: auto_adaptive_setpoint_bias
    unit_of_measurement: "°C"
    name: ${auto_adaptive_setpoint_bias}
    optimistic: true
    restore_value: true
    initial_value: 0.0
    min_value: -2.5
    max_value: 2.5
    step: 0.1
  # Temperature feedback via api
  - platform: template
    id: temperature_feedback_z1
    name: ${temperature_feedback} z1
    unit_of_measurement: "°C"
    optimistic: true
    restore_value: true
    initial_value: 20.0
    min_value: -50
    max_value: 100
    step: 0.1
  - platform: template
    id: temperature_feedback_z2
    name: ${temperature_feedback} z2
    unit_of_measurement: "°C"
    optimistic: true
    restore_value: true
    initial_value: 20.0
    min_value: -50
    max_value: 100
    step: 0.1

select:
  - platform: template
    id: temperature_feedback_source
    name: ${temperature_feedback_source}
    optimistic: true
    restore_value: true
    options:
      - "${temperature_feedback_option_room}"
      - "${select_feedback_option_api}"
    initial_option: "${temperature_feedback_option_room}"

  - platform: template
    id: heating_system_type
    name: ${heating_system_type}
    optimistic: true
    restore_value: true
    options:
      - "${heating_system_type_option_ufh}"
      - "${heating_system_type_option_ufh} *"
      - "${heating_system_type_option_ufh_rad}"
      - "${heating_system_type_option_ufh_rad} *"
      - "${heating_system_type_option_rad}" 
      - "${heating_system_type_option_rad} *"
    initial_option: "${heating_system_type_option_ufh}"
  
switch:
  - platform: template
    name: ${auto_adaptive_control_enabled}
    id: auto_adaptive_control_enabled
    restore_mode: RESTORE_DEFAULT_OFF
    optimistic: true

# button:
#   - platform: template
#     name: 'Auto-Adaptive: Run'
#     id: run_auto_adaptive_cycle
#     icon: "mdi:play-circle"
#     on_press:
#       then:
#         - script.execute: auto_adaptive_loop

interval:
  - interval: ${update_interval_minutes}
    then:
      - lambda: run_auto_adaptive_loop();
