substitutions:
  status_three_way_valve: 3-veis ventil
  status_three_way_valve_2: 3-veis ventil 2
  heatpump_climate_dhw: DHW-klima
  dhw_temp: DHW nåværende temperatur
  dhw_secondary_temp: DHW sekundær temperatur
  status_dhw_forced: DHW tvunget
  dhw_flow_temp_drop: DHW maks temperaturfall
  status_prohibit_dhw: DHW forbudt
  dhw_flow_temp_target: DHW innstilt verdi
  status_dhw_eco: DHW eco
  esp_ip: ESP IP
  internal_esp_temperature: ESP intern temperatur
  esp_sidd: ESP SSID
  uptime: ESP driftstid
  esp_version: ESP-versjon
  restart_button: ESP omstart
  status_in1_request: In1 termostat
  status_in6_request: In6 termostat 2
  status_in5_request: In5 utendørs termostat
  heatpump_select_dhw_mode: DHW-modus
  normal: Normal
  eco: Eco
  version: ESP-versjon
  led_brightness: LED lysstyrke
  led_switch: LED
  heatpump_switch_force_dhw: Tving DHW
  heatpump_switch_power_mode: Varmepumpe
  heatpump_switch_holiday: Ferie-modus kontroll
  wifi_signal_proc: WiFi-signal %
  wifi_signal_db: WiFi-signal dB
  z1_flow_temp_target: Sone 1 H/C innstilt verdi
  status_prohibit_cool_z1: Sone 1 kjøling forbudt
  status_prohibit_heating_z1: Sone 1 oppvarming forbudt
  heatpump_climate_z1: Sone 1 Turtemp
  heatpump_climate_room_z1: Sone 1 Romtemp
  z1_room_temp_target: Sone 1 rominnstilling
  z1_room_temp: Sone 1 romtemperatur
  heatpump_number_z2_set_flow_temperature: Sone 2 H/C innstilling
  z2_flow_temp_target: Sone 2 H/C innstilt verdi
  status_prohibit_cool_z2: Sone 2 kjøling forbudt
  status_prohibit_heating_z2: Sone 2 oppvarming forbudt
  heatpump_number_z2_set_room_temperature: Sone 2 rominnstilling
  heatpump_climate_z2: Sone 2 Turtemp
  heatpump_climate_room_z2: Sone 2 Romtemp
  z2_room_temp_target: Sone 2 rominnstilling
  z2_room_temp: Sone 2 romtemperatur
  mixing_tank_temp: Blandetank temperatur
  boiler_flow_temp: Kjele fremløp temperatur
  boiler_return_temp: Kjele retur temperatur
  status_booster: Booster varme
  compressor_frequency: Kompressorfrekvens
  status_compressor: Kompressor
  controller_version_text: Kontroller versjon
  controller_firmware_text: Kontroller firmware
  controller_datetime_text: Kontroller dato
  cool_consumed: Kjøling brukt
  cool_cop: Kjøle COP
  cool_delivered: Kjøling levert
  status_defrost: Avrim
  dhw_consumed: DHW brukt
  dhw_cop: DHW COP
  dhw_delivered: DHW levert
  hp_feed_temp: Fremløp temperatur
  z1_feed_temp: Z1 fremløp temperatur
  z2_feed_temp: Z2 fremløp temperatur
  flow_rate: Flytrate
  heat_source_text: Varme kilde
  heatpump: Varmepumpe
  immersion_heater: Immersjon varme
  booster_heater: Booster varme
  immersion_and_booster_heater: Immersjon + booster varme
  boiler: Kjele
  energy_consumed_increasing: Total energi brukt
  heating_consumed: Oppvarming brukt
  heating_cop: Oppvarming COP
  heating_delivered: Oppvarming levert
  status_holiday: Ferie-modus
  status_immersion: Immersjon varme
  legionella_prevention_temp: Legionella forebygging temperatur
  heatpump_select_operating_mode: Valgt driftsmodus
  heat_target_temperature: Varme måltemperatur
  heat_flow_temperature: Varme fremløp temperatur
  heat_compensation_curve: Varme kompensasjonskurve
  cool_target_temperature: Kjøle måltemperatur
  cool_flow_temperature: Kjøle fremløp temperatur
  floor_dry_up: Gulvtørking
  cool_compensation_curve: Kjølekompensasjonskurve
  operation_off: Av
  hotwater: Varmtvann
  heating: Oppvarming
  cooling: Kjøling
  frost_protection: Frostbeskyttelse
  legionella_prevention: Legionella forebygging
  runtime: Driftstid
  status_operation: Driftsmodus
  output_power: Utgangseffekt
  computed_output_power: Beregnet effekt
  computed_cop: Beregnet COP
  daily_computed_output_power: Beregnet total daglig energi
  daily_repported_input_power: Rapportert total daglig energiforbruk
  outside_temp: Utetemperatur
  hp_refrigerant_temp: Kjølemiddel væsketemperatur
  hp_refrigerant_condensing_temp: Kjølemiddel kondens temperatur
  hp_return_temp: Retur temperatur
  z1_return_temp: Z1 retur temperatur
  z2_return_temp: Z2 retur temperatur
  status_water_pump: Vannpumpe status
  status_water_pump_2: Vannpumpe 2 status
  status_water_pump_3: Vannpumpe 3 status
  status_mixing_valve: Blandingsventil status
  mixing_valve_step: Blandingsventil steg
  status_multi_zone: Multi-sone status
  status_multi_zone_idle: Inaktiv
  status_multi_zone_both: Begge
  status_multi_zone_zone1: Z1 aktiv
  status_multi_zone_zone2: Z2 aktiv
  fault_code_text: Feilkode
  refrigerant_error_code_text: Kjølemiddel feilkode
  compressor_starts: Akkumulert kompressor starter
  discharge_temp: Utløp temperatur
  ou_liquid_pipe_temp: Utendørs væskepipe 1 temp
  ou_two_phase_pipe_temp: Utendørs tofasepipe temp
  ou_suction_pipe_temp: Utendørs sugepipes temp
  ou_heatsink_temp: Utendørs varmesink temp
  ou_compressor_surface_temp: Utendørs kompressor overflatetemp
  super_heat_temp: Overoppheting temp
  sub_cool_temp: Underkjøling temp
  fan_speed: Vifte hastighet
  status_short_cycle_lockout: 'Kort syklus: Låst'
  minimum_compressor_on_time: 'Kort syklus: Minimum driftstid'
  lockout_duration: 'Kort syklus: Lås varighet (min)'
  short_cycle_mitigation_button: 'Kort syklus: Opphev lås'
  predictive_short_cycle_control_enabled: 'Kort syklus: Forebyggende Beskyttelse'
  predictive_short_cycle_high_delta_time_window: 'Kort syklus: Høy Delta Varighet'
  auto_adaptive_control_enabled: 'Autoadaptiv: Kontroll'
  heating_slope: 'Autoadaptiv: Helning Varmekurve'
  cooling_slope: 'Autoadaptiv: Helning Kjølekurve'
  maximum_heating_flow_temp: 'Autoadaptiv: Maks. Turtemperatur Varme'
  minimum_heating_flow_temp: 'Autoadaptiv: Min. Turtemperatur Varme'
  minimum_cooling_flow_temp: 'Autoadaptiv: Min. Turtemperatur Kjøling'
  cooling_smart_start_temp: 'Autoadaptiv: Smart Start Temp Kjøling'
  temperature_feedback_source: 'Autoadaptiv: Kilde for Romtemperatur'
  temperature_feedback_option_room: 'Romtermostat'
  select_feedback_option_api: 'Home Assistant / REST API'
  heating_system_type: 'Autoadaptiv: Type Varmesystem'
  heating_system_type_option_ufh: 'Gulvvarme'
  heating_system_type_option_ufh_rad: 'Gulvvarme + Radiatorer'
  heating_system_type_option_rad: 'Radiatorer'
  heating_offset_sensor: 'Autoadaptiv: Forskyvning Varme'
  cooling_offset_sensor: 'Autoadaptiv: Forskyvning Kjøling'
  auto_adaptive_setpoint_bias: 'Autoadaptiv: Settpunkt-bias'
  dynamic_learning_rate_sensor: 'Autoadaptiv: Dynamisk Læringsrate'
  temperature_feedback: 'Autoadaptiv: Tilbakemelding Nåværende Romtemperatur'
  thermostat_overshoot_compensation: 'Autoadaptiv: Kompensasjon for Termostat-overskyt'
  outside_temperature_feedback: 'Autoadaptiv: Ekstern Utetemperatur'
  outside_temperature_source: 'Autoadaptiv: Kilde for Utetemperatur'
  outside_temperature_option_internal: 'Intern Sensor'
  total_increasing_heating_consumed: Totalt Forbruk Varme
  total_increasing_heating_delivered: Totalt Levert Varme
  total_increasing_cool_consumed: Totalt Forbruk Kjøling
  total_increasing_cool_delivered: Totalt Levert Kjøling
  total_increasing_dhw_consumed: Totalt Forbruk Varmtvann
  total_increasing_dhw_delivered: Totalt Levert Varmtvann