substitutions:
  status_three_way_valve: Zawór 3-drogowy
  status_three_way_valve_2: Zawór 3-drogowy 2
  heatpump_climate_dhw: Klimat CWU
  dhw_temp: Aktualna temperatura CWU
  dhw_secondary_temp: Temperatura wtórna CWU
  status_dhw_forced: Wymuszenie CWU
  dhw_flow_temp_drop: Maksymalny spadek temperatury CWU
  status_prohibit_dhw: Zakaz CWU
  dhw_flow_temp_target: Ustawiona wartość CWU
  status_dhw_eco: Ekologiczny CWU
  esp_ip: IP ESP
  internal_esp_temperature: Temperatura wewnętrzna ESP
  esp_sidd: SSID ESP
  uptime: Czas pracy ESP
  esp_version: Wersja ESP
  restart_button: Restart ESP
  status_in1_request: Termostat In1
  status_in6_request: Termostat In6 2
  status_in5_request: Termostat zewnętrzny In5
  heatpump_select_dhw_mode: Tryb CWU
  normal: Normalny
  eco: Ekologiczny
  version: Wersja ESP
  led_brightness: Jasność LED
  led_switch: LED
  heatpump_switch_force_dhw: Wymuszenie CWU
  heatpump_switch_power_mode: Tryb grzania
  heatpump_switch_holiday: Tryb wakacyjny (sterowanie)
  wifi_signal_proc: Sygnał WiFi %
  wifi_signal_db: Sygnał WiFi dB
  z1_flow_temp_target: Ustawiona wartość Strefa 1
  status_prohibit_cool_z1: Zakaz chłodzenia Strefa 1
  status_prohibit_heating_z1: Zakaz ogrzewania Strefa 1
  heatpump_climate_z1: Strefa 1 Temp. Zasilania
  heatpump_climate_room_z1: Strefa 1 Temp. Pokojowa
  z1_room_temp_target: Ustawiona temperatura Strefa 1
  z1_room_temp: Temperatura Strefa 1
  heatpump_number_z2_set_flow_temperature: Ustawiona temperatura Strefa 2
  z2_flow_temp_target: Ustawiona wartość Strefa 2
  status_prohibit_cool_z2: Zakaz chłodzenia Strefa 2
  status_prohibit_heating_z2: Zakaz ogrzewania Strefa 2
  heatpump_number_z2_set_room_temperature: Ustawiona temperatura Strefa 2
  heatpump_climate_z2: Strefa 2 Temp. Zasilania
  heatpump_climate_room_z2: Strefa 2 Temp. Pokojowa
  z2_room_temp_target: Ustawiona temperatura Strefa 2
  z2_room_temp: Temperatura Strefa 2
  mixing_tank_temp: Temperatura zbiornika mieszającego
  boiler_flow_temp: Temperatura wody kotła
  boiler_return_temp: Temperatura powrotu kotła
  status_booster: Grzałka wspomagająca
  compressor_frequency: Częstotliwość sprężarki
  status_compressor: Sprężarka
  controller_version_text: Wersja sterownika
  controller_firmware_text: Oprogramowanie sterownika
  controller_datetime_text: Data sterownika
  cool_consumed: Chłodzenie zużyte
  cool_cop: COP chłodzenia
  cool_delivered: Chłodzenie dostarczone
  status_defrost: Odmrażanie
  dhw_consumed: CWU zużyte
  dhw_cop: COP CWU
  dhw_delivered: CWU dostarczone
  hp_feed_temp: Temperatura zasilania
  z1_feed_temp: Temperatura zasilania Z1
  z2_feed_temp: Temperatura zasilania Z2
  flow_rate: Przepływ
  heat_source_text: Źródło ciepła
  heatpump: Pompa ciepła
  immersion_heater: Grzałka elektryczna
  booster_heater: Grzałka wspomagająca
  immersion_and_booster_heater: Grzałka elektryczna i wspomagająca
  boiler: Kocioł
  energy_consumed_increasing: Całkowite zużycie energii
  heating_consumed: Ogrzewanie zużyte
  heating_cop: COP ogrzewania
  heating_delivered: Ogrzewanie dostarczone
  status_holiday: Tryb wakacyjny
  status_immersion: Grzałka elektryczna
  legionella_prevention_temp: Temperatura zapobiegania legionelli
  heatpump_select_operating_mode: Wybrany tryb pracy
  heat_target_temperature: Ustawiona temperatura grzania
  heat_flow_temperature: Temperatura zasilania grzania
  heat_compensation_curve: Krzywa kompensacji grzania
  cool_target_temperature: Ustawiona temperatura chłodzenia
  cool_flow_temperature: Temperatura zasilania chłodzenia
  floor_dry_up: Wygrzewanie Posadzki
  cool_compensation_curve: Krzywa Kompensacji Chłodzenia
  operation_off: "Wyłączony"
  hotwater: Woda grzewcza
  heating: Ogrzewanie pomieszczeń
  cooling: Chłodzenie pomieszczeń
  frost_protection: Ochrona przed mrozem
  legionella_prevention: Zapobieganie legionelli
  runtime: Czas pracy
  status_operation: Tryb pracy
  output_power: Moc wyjściowa
  computed_output_power: Szacowana moc wyjściowa
  computed_cop: Szacowany COP
  daily_computed_output_power: Szacowana całkowita dzienna produkcja energii
  daily_repported_input_power: Zgłoszone całkowite dzienne zużycie energii
  outside_temp: Temperatura zewnętrzna
  hp_refrigerant_temp: Temperatura czynnika chłodniczego
  hp_refrigerant_condensing_temp: Temperatura skraplania czynnika chłodniczego
  hp_return_temp: Temperatura powrotu
  z1_return_temp: Temperatura powrotu Z1
  z2_return_temp: Temperatura powrotu Z2
  status_water_pump: Status pompy obiegowej
  status_water_pump_2: Status pompy obiegowej 2
  status_water_pump_3: Status pompy obiegowej 3
  status_mixing_valve: Status zaworu mieszającego
  mixing_valve_step: Krok zaworu mieszającego
  status_multi_zone: Status wielu stref
  status_multi_zone_idle: Bezczynny
  status_multi_zone_both: Obie
  status_multi_zone_zone1: Z1 działa
  status_multi_zone_zone2: Z2 działa
  fault_code_text: Kod błędu
  refrigerant_error_code_text: Kod błędu czynnika chłodniczego
  compressor_starts: Liczba uruchomień sprężarki
  discharge_temp: Temperatura wylotu
  ou_liquid_pipe_temp: Temperatura rury cieczy jednostki zewnętrznej
  ou_two_phase_pipe_temp: Temperatura rury dwufazowej jednostki zewnętrznej
  ou_suction_pipe_temp: Temperatura rury ssącej jednostki zewnętrznej
  ou_heatsink_temp: Temperatura radiatora jednostki zewnętrznej
  ou_compressor_surface_temp: Temperatura powierzchni sprężarki jednostki zewnętrznej
  super_heat_temp: Temperatura przegrzania
  sub_cool_temp: Temperatura podchłodzenia
  fan_speed: Prędkość wentylatora
  status_short_cycle_lockout: 'Krótki cykl: Zablokowane'
  minimum_compressor_on_time: 'Krótki cykl: Minimalny czas pracy'
  lockout_duration: 'Krótki cykl: Czas blokady (min)'
  short_cycle_mitigation_button: 'Krótki cykl: Anuluj blokadę'
  predictive_short_cycle_control_enabled: 'Krótki cykl: Prewencja Predykcyjna'
  predictive_short_cycle_high_delta_time_window: 'Krótki cykl: Czas Trwania Wysokiej Delty'
  predictive_short_cycle_high_delta_threshold: 'Krótki cykl: Wysoki Próg Delty'
  status_predictive_boost_active: 'Krótki cykl: Wzmocnienie Predykcyjne Aktywne'
  auto_adaptive_control_enabled: 'Autoadaptacja: Sterowanie'
  maximum_heating_flow_temp: 'Autoadaptacja: Maks. Temp. Zasilania Ogrzewanie'
  minimum_heating_flow_temp: 'Autoadaptacja: Min. Temp. Zasilania Ogrzewanie'
  minimum_cooling_flow_temp: 'Autoadaptacja: Min. Temp. Zasilania Chłodzenie'
  cooling_smart_start_temp: 'Autoadaptacja: Inteligentna Temp. Startu Chłodzenia'
  temperature_feedback_source: 'Autoadaptacja: Źródło Temperatury w Pomieszczeniu'
  temperature_feedback_option_room: 'Termostat Pokojowy'
  select_feedback_option_api: 'Home Assistant / REST API'
  select_feedback_option_asgard_vt: 'Wirtualny Termostat Asgard'
  heating_system_type: 'Autoadaptacja: Typ Systemu Grzewczego'
  heating_system_type_option_ufh: 'Ogrzewanie Podłogowe'
  heating_system_type_option_ufh_rad: 'Ogrzewanie Podłogowe + Grzejniki'
  heating_system_type_option_rad: 'Grzejniki'
  auto_adaptive_setpoint_bias: 'Autoadaptacja: Przesunięcie Wartości Zadanej'
  temperature_feedback: 'Autoadaptacja: Sprzężenie Zwrotne Aktualnej Temperatury'
  defrost_risk_handling_enabled: 'Autoadaptacja: Redukcja Odszraniania'
  smart_boost_enabled: 'Autoadaptacja: Inteligentny Boost'
  total_increasing_heating_consumed: Całkowite Zużycie Ogrzewanie
  total_increasing_heating_delivered: Całkowita Produkcja Ogrzewanie
  total_increasing_cool_consumed: Całkowite Zużycie Chłodzenie
  total_increasing_cool_delivered: Całkowita Produkcja Chłodzenie
  total_increasing_dhw_consumed: Całkowite Zużycie CWU
  total_increasing_dhw_delivered: Całkowita Produkcja CWU
  pump_speed: 'Prędkość Pompy'
  pump_feedback: 'Zużycie Pompy'
  pump_feedback_status: 'Status Informacji Zwrotnej Pompy'
  master_thermostat: 'Główny Czujnik Pokojowy'

  solver_kwh_meter_feedback_source: "Źródło licznika energii"
  solver_kwh_meter_option_internal: "Wewnętrzny licznik energii"
  solver_kwh_meter_feedback: "Sprzężenie zwrotne licznika"

  asgard_vt_temp_sensor_source: 'Źródło Wirtualnego Termostatu'