globals:
  - id: last_heating_consumed_update_day
    type: int
    restore_value: yes
    initial_value: '-1'
  - id: last_heating_produced_update_day
    type: int
    restore_value: yes
    initial_value: '-1'
  - id: last_cooling_consumed_update_day
    type: int
    restore_value: yes
    initial_value: '-1'
  - id: last_cooling_produced_update_day
    type: int
    restore_value: yes
    initial_value: '-1'
  - id: last_dhw_consumed_update_day
    type: int
    restore_value: yes
    initial_value: '-1'
  - id: last_dhw_produced_update_day
    type: int
    restore_value: yes
    initial_value: '-1'

sensor:
  - platform: ecodan
    cool_cop:
      id: cool_cop
      name: ${cool_cop}
    heating_cop:
      id: heating_cop
      name: ${heating_cop}    
    dhw_cop:
      id: ddhw_cop
      name: ${dhw_cop}

    cool_consumed:
      id: cool_consumed
      name: ${cool_consumed}
      filters:
        - filter_out: nan
      on_value:
        - lambda: |-
            auto& status = id(ecodan_instance).get_status();
            int today = status.day_of_year();
            if (today == -1) return;

            int last_day = id(last_cooling_consumed_update_day);

            if (last_day == -1) {
              id(last_cooling_consumed_update_day) = today;
              last_day = today;
            }

            if (today != last_day) {
              float current = id(sensor_cooling_consumed_total).state;
              if (std::isnan(current)) current = 0.0f;
              id(sensor_cooling_consumed_total).publish_state(current + x);
              id(last_cooling_consumed_update_day) = today;
            }

    cool_delivered:
      id: cool_delivered
      name: ${cool_delivered}
      filters:
        - filter_out: nan
      on_value:
        - lambda: |-
            auto& status = id(ecodan_instance).get_status();
            int today = status.day_of_year();
            if (today == -1) return;

            int last_day = id(last_cooling_produced_update_day);

            if (last_day == -1) {
              id(last_cooling_produced_update_day) = today;
              last_day = today;
            }

            if (today != last_day) {
              float current = id(sensor_cooling_produced_total).state;
              if (std::isnan(current)) current = 0.0f;
              id(sensor_cooling_produced_total).publish_state(current + x);
              id(last_cooling_produced_update_day) = today;
            }

    heating_consumed:
      id: heating_consumed
      name: ${heating_consumed}
      filters:
        - filter_out: nan
      on_value:
        - lambda: |-
            auto& status = id(ecodan_instance).get_status();
            int today = status.day_of_year();
            if (today == -1) return;

            int last_day = id(last_heating_consumed_update_day);

            if (last_day == -1) {
              id(last_heating_consumed_update_day) = today;
              last_day = today;
            }

            if (today != last_day) {
              float current = id(sensor_heating_consumed_total).state;
              if (std::isnan(current)) current = 0.0f;
              id(sensor_heating_consumed_total).publish_state(current + x);
              id(last_heating_consumed_update_day) = today;
            }

    heating_delivered:
      id: heating_delivered
      name: ${heating_delivered}
      filters:
        - filter_out: nan
      on_value:
        - lambda: |-
            auto& status = id(ecodan_instance).get_status();
            int today = status.day_of_year();
            if (today == -1) return;

            int last_day = id(last_heating_produced_update_day);

            if (last_day == -1) {
              id(last_heating_produced_update_day) = today;
              last_day = today;
            }

            if (today != last_day) {
              float current = id(sensor_heating_produced_total).state;
              if (std::isnan(current)) current = 0.0f;
              id(sensor_heating_produced_total).publish_state(current + x);
              id(last_heating_produced_update_day) = today;
            }

    dhw_consumed:
      id: dhw_consumed
      name: ${dhw_consumed}
      filters:
        - filter_out: nan
      on_value:
        - lambda: |-
            auto& status = id(ecodan_instance).get_status();
            int today = status.day_of_year();
            if (today == -1) return;

            int last_day = id(last_dhw_consumed_update_day);

            if (last_day == -1) {
              id(last_dhw_consumed_update_day) = today;
              last_day = today;
            }

            if (today != last_day) {
              float current = id(sensor_dhw_consumed_total).state;
              if (std::isnan(current)) current = 0.0f;
              id(sensor_dhw_consumed_total).publish_state(current + x);
              id(last_dhw_consumed_update_day) = today;
            }

    dhw_delivered:
      id: dhw_delivered
      name: ${dhw_delivered}
      filters:
        - filter_out: nan
      on_value:
        - lambda: |-
            auto& status = id(ecodan_instance).get_status();
            int today = status.day_of_year();
            if (today == -1) return;

            int last_day = id(last_dhw_produced_update_day);

            if (last_day == -1) {
              id(last_dhw_produced_update_day) = today;
              last_day = today;
            }

            if (today != last_day) {
              float current = id(sensor_dhw_produced_total).state;
              if (std::isnan(current)) current = 0.0f;
              id(sensor_dhw_produced_total).publish_state(current + x);
              id(last_dhw_produced_update_day) = today;
            }

  - platform: template
    name: ${total_increasing_heating_consumed}
    id: sensor_heating_consumed_total
    unit_of_measurement: 'kWh'
    device_class: energy
    state_class: total_increasing
    accuracy_decimals: 2
    update_interval: never
      
  - platform: template
    name: ${total_increasing_heating_delivered}
    id: sensor_heating_produced_total
    unit_of_measurement: 'kWh'
    device_class: energy
    state_class: total_increasing
    accuracy_decimals: 2
    update_interval: never
      
  - platform: template
    name: ${total_increasing_cool_consumed}
    id: sensor_cooling_consumed_total
    unit_of_measurement: 'kWh'
    device_class: energy
    state_class: total_increasing
    accuracy_decimals: 2
    update_interval: never
      
  - platform: template
    name: ${total_increasing_cool_delivered}
    id: sensor_cooling_produced_total
    unit_of_measurement: 'kWh'
    device_class: energy
    state_class: total_increasing
    accuracy_decimals: 2
    update_interval: never
      
  - platform: template
    name: ${total_increasing_dhw_consumed}
    id: sensor_dhw_consumed_total
    unit_of_measurement: 'kWh'
    device_class: energy
    state_class: total_increasing
    accuracy_decimals: 2
    update_interval: never
      
  - platform: template
    name: ${total_increasing_dhw_delivered}
    id: sensor_dhw_produced_total
    unit_of_measurement: 'kWh'
    device_class: energy
    state_class: total_increasing
    accuracy_decimals: 2
    update_interval: never