esphome:
  name: ${name}
  friendly_name: ${friendlyName}
  platformio_options:
    board_build.flash_mode: dio
  project:
    name: Gekkekoe.Ecodan ESPHome Heatpump
    version: "VERSION"

esp32:
  board: esp32-s3-devkitc-1
  framework:
    type: esp-idf
    version: recommended
    # Custom sdkconfig options
    sdkconfig_options:
      COMPILER_OPTIMIZATION_SIZE: y

# enable ota update via http request
http_request:
  buffer_size_tx: 20248

ota:
  - platform: http_request

update:
  - platform: http_request
    name: Firmware Update
    source: https://github.com/gekkekoe/esphome-ecodan-hp/releases/latest/download/manifest-esp32s3-proxy2.json
  
uart:
  - id: uart_ecodan
    rx_pin:
      number: GPIO38
      mode:
        input: true
        pullup: true
    tx_pin:
      number: GPIO39
      mode:
        output: true
    baud_rate: 2400
    parity: EVEN
    stop_bits: 1
    # debug:
    #   direction: BOTH
    #   dummy_receiver: false
    #   after:
    #     delimiter: "\n"
    #   sequence:
    #     - lambda: UARTDebug::log_hex(direction, bytes, ' ');

  - id: uart_proxy
    rx_pin:
      number: GPIO8
      mode:
        input: true
        pullup: true
    tx_pin:
      number: GPIO7
      mode:
        output: true
    baud_rate: 9600
    parity: EVEN
    stop_bits: 1
    # debug:
    #   direction: BOTH
    #   dummy_receiver: false
    #   after:
    #     delimiter: "\n"
    #   sequence:
    #     - lambda: UARTDebug::log_hex(direction, bytes, ' ');  

ecodan:
  uart_id: uart_main
  proxy_uart_id: uart_proxy

###  ESP restart button
button:
  - platform: restart
    id: restart_button
    name: ${restart_button}

sensor:
  - platform: internal_temperature
    name: ${internal_esp_temperature}
    entity_category: diagnostic