esphome:
  name: ${name}
  friendly_name: ${friendlyName}
  platformio_options:
    board_build.flash_mode: dio

esp32:
  board: esp32dev
  framework:
    type: esp-idf
    version: recommended
    # Custom sdkconfig options
    sdkconfig_options:
      COMPILER_OPTIMIZATION_SIZE: y

uart:
  id: uart_ecodan
  rx_pin:
    number: GPIO2
    mode:
      input: true
      pullup: true
  tx_pin:
    number: GPIO1
    mode:
      output: true
  baud_rate: 2400
  parity: EVEN
  stop_bits: 1
  debug:
    direction: BOTH
    dummy_receiver: false
    after:
      delimiter: "\n"
    sequence:
      - lambda: UARTDebug::log_hex(direction, bytes, ' ');

sensor:
  - platform: internal_temperature
    name: ${internal_esp_temperature}
    entity_category: diagnostic
    unit_of_measurement: "°C"
    device_class: temperature