substitutions:
  uart_rx_pin: 38
  uart_tx_pin: 39
  uart_proxy_rx_pin: 8
  uart_proxy_tx_pin: 7

<<: !include proxy-base.yaml
<<: !include esp32s3-led.yaml
<<: !include slave.yaml

sensor:
  - platform: internal_temperature
    name: ${internal_esp_temperature}
    entity_category: diagnostic
    unit_of_measurement: "°C"
    device_class: temperature
    accuracy_decimals: 1