substitutions:
  is_internal_asgard_only: "true"

number:
 # Overridable solver inputs
  - platform: template
    id: num_raw_heat_produced
    name: ${num_raw_heat_produced}
    internal: ${is_internal_asgard_only}
    optimistic: true
    restore_value: true
    initial_value: 0.0
    min_value: 0.0
    max_value: 200.0
    step: 0.1

  - platform: template
    id: num_raw_elec_consumed
    name: ${num_raw_elec_consumed}
    internal: ${is_internal_asgard_only}
    optimistic: true
    restore_value: true
    initial_value: 0.0
    min_value: 0.0
    max_value: 100.0
    step: 0.1

  - platform: template
    id: num_raw_runtime_hours
    name: ${num_raw_runtime_hours}
    internal: ${is_internal_asgard_only}
    optimistic: true
    restore_value: true
    initial_value: 0.0
    min_value: 0.0
    max_value: 24.0
    step: 0.1

  - platform: template
    id: num_raw_avg_outside_temp
    name: ${num_raw_avg_outside_temp}
    internal: ${is_internal_asgard_only}
    optimistic: true
    restore_value: true
    initial_value: 7.0
    min_value: -25.0
    max_value: 40.0
    step: 0.1

  - platform: template
    id: num_raw_avg_room_temp
    name: ${num_raw_avg_room_temp}
    internal: ${is_internal_asgard_only}
    optimistic: true
    restore_value: true
    initial_value: 20.0
    min_value: 10.0
    max_value: 35.0
    step: 0.1

  - platform: template
    id: num_raw_delta_room_temp
    name: ${num_raw_delta_room_temp}
    internal: ${is_internal_asgard_only}
    optimistic: true
    restore_value: true
    initial_value: 0.0
    min_value: 0.0
    max_value: 10.0
    step: 0.1
  
  - platform: template
    name: "Raw Max Output Power"
    id: num_raw_max_output
    internal: ${is_internal_asgard_only}
    initial_value: 7.0
    min_value: 1.0
    max_value: 20.0
    step: 0.1
    optimistic: true
    restore_value: true
    unit_of_measurement: "kW"
    icon: "mdi:flash"

  - platform: template
    id: num_battery_soc_kwh
    name: ${num_battery_soc_kwh}
    internal: ${is_internal_asgard_only}
    icon: mdi:battery-charging
    optimistic: true
    restore_value: true
    initial_value: 0.0
    min_value: 0.0
    max_value: 100.0
    step: 0.1
    unit_of_measurement: kWh

  - platform: template
    id: num_battery_max_discharge_kw
    name: ${num_battery_max_discharge_kw}
    internal: ${is_internal_asgard_only}
    icon: mdi:lightning-bolt
    optimistic: true
    restore_value: true
    initial_value: 3.0
    min_value: 0.5
    max_value: 15.0
    step: 0.1
    unit_of_measurement: kW

  - platform: template
    id: num_raw_hl_tm_product
    name: ${num_raw_hl_tm_product}
    internal: ${is_internal_asgard_only}
    unit_of_measurement: "kWh²/K"
    optimistic: true
    restore_value: true
    initial_value: 0.0
    min_value: 0.0
    max_value: 300.0
    step: 0.001

  - platform: template
    name: ${num_raw_solar_factor}
    id: num_raw_solar_factor
    internal: ${is_internal_asgard_only}
    optimistic: true
    restore_value: true
    initial_value: 0.015
    min_value: 0.001
    max_value: 0.05
    step: 0.001

  - platform: template
    name: "Odin DHW Start Threshold"
    id: dhw_start_threshold
    internal: ${is_internal_asgard_only}
    min_value: 0.0
    max_value: 20.0
    step: 0.5
    optimistic: true
    restore_value: true
    initial_value: 0.0
    icon: "mdi:thermometer-water"
    entity_category: "config"