
captive_portal:
  id: id_captive_portal

text_sensor:
  - platform: wifi_info
    ip_address:
      name: ${esp_ip}
      icon: mdi:ip
    ssid:
      name: ${esp_sidd}
      icon: mdi:wifi

sensor:
  - platform: wifi_signal # Reports the WiFi signal strength/RSSI in dB
    name: ${wifi_signal_db}
    id: wifi_signal_db
    update_interval: 5s
    entity_category: diagnostic
  - platform: copy # Reports the WiFi signal strength in %
    source_id: wifi_signal_db
    name: ${wifi_signal_proc}
    id: wifi_signal_proc
    filters:
      - lambda:
          float strength = 2 * (x + 100.0);
          return clamp(strength, 0.0f, 100.0f);
    unit_of_measurement: " %"
    entity_category: diagnostic
    device_class: ""
    icon: mdi:wifi