binary_sensor:
  - platform: ecodan
    status_prohibit_heating_z2:
      id: status_prohibit_heating_z2
      name: ${status_prohibit_heating_z2}
    status_prohibit_cool_z2:
      id: status_prohibit_cool_z2
      name: ${status_prohibit_cool_z2}
    status_three_way_valve_2:
      id: status_three_way_valve_2
      name: ${status_three_way_valve_2}
    status_water_pump_3:
      id: status_water_pump_3
      name: ${status_water_pump_3}

climate:
  - platform: ecodan
    heatpump_climate_z2:
      name: ${heatpump_climate_z2}
      id: heatpump_climate_z2
      get_status_func: |-
        return id(ecodan_instance).get_status();
      get_target_temp_func: |-
        auto& status = id(ecodan_instance).get_status();
        auto mode = status.HeatingCoolingMode;
        switch (mode) {
            case esphome::ecodan::Status::HpMode::HEAT_FLOW_TEMP:
            case esphome::ecodan::Status::HpMode::COOL_FLOW_TEMP:
            case esphome::ecodan::Status::HpMode::HEAT_COMPENSATION_CURVE:
              return status.Zone2FlowTemperatureSetPoint;
            break;
            case esphome::ecodan::Status::HpMode::COOL_ROOM_TEMP:
            case esphome::ecodan::Status::HpMode::HEAT_ROOM_TEMP:
              return status.Zone2SetTemperature;
            break;
            default:
              return NAN;
        }      
      target_temp_func: |-
        auto& status = id(ecodan_instance).get_status();
        auto mode = status.HeatingCoolingMode;
        switch (mode) {
            case esphome::ecodan::Status::HpMode::HEAT_FLOW_TEMP:
            case esphome::ecodan::Status::HpMode::COOL_FLOW_TEMP:
              id(ecodan_instance).set_flow_target_temperature(x, esphome::ecodan::SetZone::ZONE_2);
            break;
            case esphome::ecodan::Status::HpMode::COOL_ROOM_TEMP:
            case esphome::ecodan::Status::HpMode::HEAT_ROOM_TEMP:
              id(ecodan_instance).set_room_temperature(x, esphome::ecodan::SetZone::ZONE_2);
            break;                    
            default:
              break;
        }
      current_temp_func: |-
        auto& status = id(ecodan_instance).get_status();
        auto mode = status.HeatingCoolingMode;
        switch (mode) {
            case esphome::ecodan::Status::HpMode::HEAT_FLOW_TEMP:
            case esphome::ecodan::Status::HpMode::COOL_FLOW_TEMP:
            case esphome::ecodan::Status::HpMode::HEAT_COMPENSATION_CURVE:
              return status.Zone2FlowTemperatureSetPoint;
            break;
            case esphome::ecodan::Status::HpMode::COOL_ROOM_TEMP:
            case esphome::ecodan::Status::HpMode::HEAT_ROOM_TEMP:
              return status.Zone2RoomTemperature;
            break;
            default:
              return NAN;                    
        } 
    heatpump_climate_room_z2:
      name: ${heatpump_climate_room_z2}
      id: heatpump_climate_room_z2
      thermostat_climate_mode: true
      get_status_func: |-
        return id(ecodan_instance).get_status();
      get_target_temp_func: |-
        auto& status = id(ecodan_instance).get_status();
        return status.Zone2SetTemperature;
      target_temp_func: |-
        id(ecodan_instance).set_room_temperature(x, esphome::ecodan::SetZone::ZONE_2);
      current_temp_func: |-
        auto& status = id(ecodan_instance).get_status();
        return status.Zone2RoomTemperature;

sensor:
  - platform: ecodan
    z2_flow_temp_target:
      id: z2_flow_temp_target
      name: ${z2_flow_temp_target}
    z2_room_temp:
      id: z2_room_temp
      name: ${z2_room_temp}      
    z2_room_temp_target:
      id: z2_room_temp_target
      name: ${z2_room_temp_target}
    z2_feed_temp:
      id: z2_feed_temp
      name: ${z2_feed_temp}
    z2_return_temp:
      id: z2_return_temp
      name: ${z2_return_temp}
    mixing_valve_step:
      id: mixing_valve_step
      name: ${mixing_valve_step}
    status_mixing_valve:
      id: status_mixing_valve
      name: ${status_mixing_valve}

    status_heating_cooling_z2:
      id: status_heating_cooling_z2
      name: H/C status z2
      internal: true
      on_value:
        if:
          condition:
            - lambda: |-
                auto mode = static_cast<uint8_t>(id(ecodan_instance).get_status().HeatingCoolingModeZone2);
                auto index = id(heatpump_select_operating_mode_z2).active_index();
                return (index.has_value() && index.value() != mode);
          then:
            - select.set_index:
                id: heatpump_select_operating_mode_z2
                index: !lambda "return static_cast<uint8_t>(id(ecodan_instance).get_status().HeatingCoolingModeZone2);"

select:
  - platform: template
    name: z2 ${heatpump_select_operating_mode}
    id: heatpump_select_operating_mode_z2
    optimistic: true
    restore_value: true
    options:
      - ${heat_target_temperature}
      - ${heat_flow_temperature}
      - ${heat_compensation_curve}
      - ${cool_target_temperature}
      - ${cool_flow_temperature}
    set_action:
      - lambda: |-
          auto index = id(heatpump_select_operating_mode_z2).index_of(x);
          auto active_index = id(heatpump_select_operating_mode_z2).active_index();
          if (index.has_value() && index.value() != active_index.value()) {
            id(ecodan_instance).set_hp_mode(static_cast<uint8_t>(index.value()), esphome::ecodan::SetZone::ZONE_2);
          }